/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as MacrosIndexRouteImport } from './routes/macros/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as WikiDefIdRouteImport } from './routes/wiki/$defId'
import { Route as MacrosSlugRouteImport } from './routes/macros/$slug'
import { Route as EditorDefIdRouteImport } from './routes/editor/$defId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosIndexRoute = MacrosIndexRouteImport.update({
  id: '/macros/',
  path: '/macros/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiDefIdRoute = WikiDefIdRouteImport.update({
  id: '/wiki/$defId',
  path: '/wiki/$defId',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosSlugRoute = MacrosSlugRouteImport.update({
  id: '/macros/$slug',
  path: '/macros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDefIdRoute = EditorDefIdRouteImport.update({
  id: '/editor/$defId',
  path: '/editor/$defId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor/$defId': typeof EditorDefIdRoute
  '/macros/$slug': typeof MacrosSlugRoute
  '/wiki/$defId': typeof WikiDefIdRoute
  '/account': typeof AccountIndexRoute
  '/editor': typeof EditorIndexRoute
  '/macros': typeof MacrosIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$defId': typeof EditorDefIdRoute
  '/macros/$slug': typeof MacrosSlugRoute
  '/wiki/$defId': typeof WikiDefIdRoute
  '/account': typeof AccountIndexRoute
  '/editor': typeof EditorIndexRoute
  '/macros': typeof MacrosIndexRoute
  '/wiki': typeof WikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor/$defId': typeof EditorDefIdRoute
  '/macros/$slug': typeof MacrosSlugRoute
  '/wiki/$defId': typeof WikiDefIdRoute
  '/account/': typeof AccountIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/macros/': typeof MacrosIndexRoute
  '/wiki/': typeof WikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor/$defId'
    | '/macros/$slug'
    | '/wiki/$defId'
    | '/account'
    | '/editor'
    | '/macros'
    | '/wiki'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor/$defId'
    | '/macros/$slug'
    | '/wiki/$defId'
    | '/account'
    | '/editor'
    | '/macros'
    | '/wiki'
  id:
    | '__root__'
    | '/'
    | '/editor/$defId'
    | '/macros/$slug'
    | '/wiki/$defId'
    | '/account/'
    | '/editor/'
    | '/macros/'
    | '/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorDefIdRoute: typeof EditorDefIdRoute
  MacrosSlugRoute: typeof MacrosSlugRoute
  WikiDefIdRoute: typeof WikiDefIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  MacrosIndexRoute: typeof MacrosIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/': {
      id: '/macros/'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof MacrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$defId': {
      id: '/wiki/$defId'
      path: '/wiki/$defId'
      fullPath: '/wiki/$defId'
      preLoaderRoute: typeof WikiDefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/$slug': {
      id: '/macros/$slug'
      path: '/macros/$slug'
      fullPath: '/macros/$slug'
      preLoaderRoute: typeof MacrosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$defId': {
      id: '/editor/$defId'
      path: '/editor/$defId'
      fullPath: '/editor/$defId'
      preLoaderRoute: typeof EditorDefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorDefIdRoute: EditorDefIdRoute,
  MacrosSlugRoute: MacrosSlugRoute,
  WikiDefIdRoute: WikiDefIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  MacrosIndexRoute: MacrosIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
